dbt_arghyam:
  outputs:
    intermediate:
      dbname: dalgo
      host: dalgo.cdybo3vdnbcr.ap-south-1.rds.amazonaws.com
      password: purityWater47isnotAquafina
      port: 5432
      schema: intermediate
      threads: 8
      type: postgres
      user: dalgo
  target: intermediate

