name: Our first dbt PR job

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt build
        run: dbt build --full-refresh --profiles-dir ./
        env:
          POSTGRES_DBNAME: ${{ secrets.POSTGRES_DBNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}

      # Ensure SQLFluff has dbt context and profiles for linting
      - name: Lint models
        run: |
          # Set up the DBT_PROFILES_DIR if it's not in the root directory
          export DBT_PROFILES_DIR=$GITHUB_WORKSPACE
          # Run SQLFluff lint with dbt integration and point to your profiles directory
          sqlfluff lint models --dialect dbt
        env:
          DBT_PROFILES_DIR: "./"  # Adjust if your profiles are in a different directory

      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
