name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dbt dependencies
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres # Specify dbt adapter for your database

      # Set up environment variables (DBT profile)
      - name: Set up environment variables
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_PORT: ${{ secrets.DBT_PORT }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

      # Run dbt clean
      - name: dbt clean
        run: dbt clean

      # Run dbt deps
      - name: dbt deps
        run: dbt deps

      # Run dbt test
      - name: dbt test
        run: dbt test
