name: Our first dbt PR job

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Install dbt dependencies
        run: dbt deps

      # Verify SQLFluff installation
      - name: Verify SQLFluff Installation
        run: sqlfluff --version

      # List models directory to confirm accessibility of files
      - name: List models directory
        run: ls -R models

      # Run SQLFluff Lint in human-readable format as a dry run
      - name: Run SQLFluff Lint (dry run)
        run: sqlfluff lint models --dialect postgres --disregard-sqlfluffignores -v

      # Run SQLFluff Lint with JSON output if dry run succeeds
      - name: Run SQLFluff Lint with JSON Output
        run: sqlfluff lint models --dialect postgres --format json --disregard-sqlfluffignores > sqlfluff_coverage.json

      # Upload JSON report to Codecov
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: sqlfluff_coverage.json
          flags: sqlfluff
          name: "SQLFluff Lint Coverage"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
