name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dbt dependencies
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres # Replace with the correct adapter if using a different one

      # Step 4: Run dbt clean
      - name: dbt clean
        run: dbt clean

      # Step 5: Run dbt deps
      - name: dbt deps
        run: dbt deps

      # Step 6: Run dbt test
      - name: dbt test
        run: dbt test
