name: Our first dbt PR job
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install requirements
        run: pip install -r requirements.txt  

      - name: Install dbt dependencies
        run: dbt deps

      # Lint models and save output to XML
      - name: Lint models
        run: "sqlfluff lint models --format json > sqlfluff_coverage.json"

      - name: Convert JSON to XML
        run: |
          python -c "
          import json, dicttoxml
          with open('sqlfluff_coverage.json') as json_file:
              data = json.load(json_file)
          xml_data = dicttoxml.dicttoxml(data, custom_root='coverage', attr_type=False)
          with open('sqlfluff_coverage.xml', 'wb') as xml_file:
              xml_file.write(xml_data)
          "
        shell: bash

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: sqlfluff_coverage.xml
          flags: sqlfluff
          name: "SQLFluff Lint Coverage"
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}


