name: dbt Slim CI

on:
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  dbt-slim-ci:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dbt and dependencies
      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres  # Replace with the appropriate adapter for your database

      # Step 4: Generate and store manifest for the main branch (for state comparison)
      - name: Generate dbt manifest for main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          dbt compile --target-path=prod-run-artifacts
          git add prod-run-artifacts/manifest.json
          git commit -m "Update main branch manifest for Slim CI"
          git push

      # Step 5: Generate feature branch manifest for comparison
      - name: Generate feature branch manifest
        run: dbt compile

      # Step 6: List modified models using Slim CI pattern
      - name: List modified models
        id: modified_models
        run: |
          OUTPUT=$(dbt ls --select state:modified+ --defer --state=prod-run-artifacts)
          echo "::set-output name=modified_models::$OUTPUT"

      # Step 7: Run dbt only on modified models
      - name: Run dbt on modified models
        if: steps.modified_models.outputs.modified_models != ''
        run: |
          dbt run --select state:modified+ --defer --state=prod-run-artifacts
