name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environmentss
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dbt dependencies
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-postgres # Replace with your dbt adapter if different

      # Step 4: Set up environment variables for dbt profile
      # This doesn't have a `run` or `uses` key because it only sets environment variables for the following steps
      - name: Set up environment variables
        run: echo "Setting up environment variables"
        env:
          DBT_USER: ${{ secrets.DBT_USER }}
          DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_PORT: ${{ secrets.DBT_PORT }}
          DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
          DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}

      # Step 5: Run dbt clean
      - name: dbt clean
        run: dbt clean

      # Step 6: Run dbt deps
      - name: dbt deps
        run: dbt deps

      # Step 7: Run dbt test
      - name: dbt test
        run: dbt test
